spring:
  datasource:
    url: 'jdbc:h2:file:C:/h2/data' # H2 DB 연결 주소 (Embedded Mode) // H2 콘솔 활성화
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8083